yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Construction Barrel
      - Stop Sign
      - One Way Left
      - One Way Right
      - Road Closed
      - Pedestrian
      - No Turns


